import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MEMO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-700`}
      >
                <header className=" p-5 md:p-8 bg-white m-2 rounded overflow-hidden shadow items-center">
                  <nav className="flex justify-between align-middle">
                      <h3 className="uppercase text-xl md:text-3xl text-violet-400 font-bold ">memo</h3>
                  </nav>
                </header>
        {children}
      </body>
    </html>
  );
}